package com.istudio.googleads.modules.banner_adds.demos.demo_list_ad

object MockMenuItem {

    val menuItems = listOf(
        MenuItem("Cherry Avocado -- 1", "cherries, garlic, serrano, mayo", "$7.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Fried Baby Onions -- 2", "maple syrup, walnut salsa, sauce", "$11.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Fried Rice -- 3", "red onion, kale, puffed wild rice", "$10.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Beet Fries -- 4", "cilantro, raw beet, feta, sumac", "$9.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Sautéed Spaghetti -- 5", "garlic, poached egg, almonds", "$12.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Grape Toast -- 6", "red cabbage, sweet onion, beef", "$14.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Fresh Acorn Squash -- 7", "pumplin mole, pomegranate, seed", "$11.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Quad Burgers -- 8", "biscuits, bacon, honey butter", "$7.00", "Dinner", "menu_item_image"),
        MenuItem("The Mister Burger -- 9", "pepperoni, cheese, lettuce fries", "$16.00", "Dinner", "menu_item_image"),
        MenuItem("Deep Fried String Cheese -- 10", "dipped in a honey mustard aioli", "$7.00", "Dinner", "menu_item_image"),
        MenuItem("Cheese Plate -- 11", "a bunch of different types of cheeses", "$16.00", "Dinner", "menu_item_image"),
        MenuItem("Pear and Jicama -- 12", "cheese, chardonnay vinaigrette", "$12.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("The Caesar -- 13", "garlic dressing, egg, olive oil, walnut breadcrumbs", "$10.00", "Dinner - Veggies, Grains, Salads", "menu_item_image"),
        MenuItem("Cold Brussels Sprouts -- 14", "shaved, raisins", "$10.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Deep Fried Brussels Sprouts -- 15", "smoked yogurt and tea", "$12.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Bread & Whipped Cream -- 16", "bread with whipped cream", "$3.00", "Dinner - Salads", "menu_item_image"),
        MenuItem("Lamb Steaks -- 17", "fregola, cucumber, lemon, rosemary", "$15.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Grilled Pork Chop -- 18", "scallion-cilantro salad, chili", "$14.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Lobster Dumplings -- 19", "chili oil, garlic, celery", "$16.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("Grilled Scallops -- 20", "hummus, crispy fries", "$16.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("White Tuna -- 21", "crispy garlic, green olives, oil", "$15.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("Oysters -- 22", "cilantro, kale, lemons", "$3.50", "Dinner - Seafood", "menu_item_image"),
        MenuItem("Crab legs -- 23", "quinoa, kumquat, black garlic", "$15.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("Lobster Rolls and Tuna -- 24", "ahi tuna, cucumber, tomato", "$14.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("King Salmon -- 25", "maple glaze, tomato, cucumber, lemon", "$30.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("Tempura Tacos -- 26", "olive aioli, radish salad", "$16.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("Grilled Pork Belly -- 27", "sweet soya, charred scallion", "$15.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Singaporean Fried Chicken -- 28", "green onion, sweet heat", "$7.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Live Quail -- 29", "crisp potatoes, cumin syrup, mushrooms", "$15.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Raw Beef -- 30", "raw beef, beech mushrooms, coddled egg", "$13.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Mac 'n Cheese -- 31", "fried mortadella, white cheddar", "$10.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Blackened Ribeye Steak -- 32", "beef, cheese, beans, lemon", "$56.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Braised Beef Tacos -- 33", "salsa salad, corn tortillas", "$15.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Smoked Duck -- 34", "blood orange, carrot, cocoa, raisins", "$13.00", "Dinner - Meat", "menu_item_image"),
        MenuItem("Shrimp & Grits -- 35", "shrimp, grits, fries, lemon", "$16.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("Mussels -- 36", "spiced butter, toasted bread herb salad", "$14.00", "Dinner - Seafood", "menu_item_image"),
        MenuItem("Beer Burger -- 37", "beer of the day on a burger", "$10.00", "Dinner", "menu_item_image"),
        MenuItem("Sundae -- 38", "maple ice cream, blueberry, graham cracker", "$7.00", "Dinner - Sweet", "menu_item_image"),
        MenuItem("Honey Ice Cream -- 39", "toasted nuts, dried fruits", "$7.00", "Dinner - Sweet", "menu_item_image"),
        MenuItem("Chocolate Cake -- 40", "orange almonds", "$7.00", "Dinner - Sweet", "menu_item_image"),
        MenuItem("Toffee Pudding -- 41", "dates, toffee, seeds", "$7.00", "Dinner - Sweet", "menu_item_image")
    )
}